DynamoDS/PackageManagerClient

src/GregClient/GregClient.csproj, src/GregClient/Requests/TermsOfUse.cs, src/GregClient/Responses/Responses.cs, src/GregClientSandbox/GregClientSandbox.csproj
Background
-----
This is the .NET client counterpart of [the *Terms of Use* web APIs](https://github.com/DynamoDS/GReg/pull/1). It will be consumed by DynamoCore to determine if a given publisher has accepted the terms of use prior to publishing a new package.
Hi @pboyer, please have a look at this while we [add more code](https://github.com/DynamoDS/Dynamo/pull/4254) to make use of this .NET client in DynamoCore. Do I miss anything here? It feels too small an implementation. Thanks!
=> Added terms of use related requests/responses

README.md, src/GregClient/GregClient.csproj, src/GregClient/Requests/BanPackage.cs
This pull request implements client-side API that works with [its REST counterparts](https://github.com/DynamoDS/GReg/pull/2). More details can be found on that pull request.
NOTE: We may or may not require this, it all depends on how we expose the functionality of banning a package. This should only be allowed for internal teammates, so we may end up exposing a web-page that allows banning/unbanning a package.
@pboyer, please have a look. If you have an idea of how we expose this banning functionality to only internal teammates (e.g. some site served only on ADS domain), then I'd love to hear from you. Thanks!
=> Implemented client-side APIs to ban/unban packages

src/GregClient/GregClient.cs, src/GregClientSandbox/Program.cs
This PR adds error handling to the `ExecuteAndDeserializeWithContent<T>(...)` method. If the request returns a 404 (Not Found), this method will now return null. Previously, this method returned the response to the parser which then failed because the response's content was empty. The documentation for the method has been updated to indicate that the method will now return null if there was an error in executing the message.
When this PR is merged, a new GregClient NuGet will be generated an uploaded to nuget.org. That NuGet will then be referenced in Reach, and a PR will be issued for Reach.
PTAL: 
@mjkkirschner 
FYI:
@sharadkjaiswal
=> Catch whitelist 404 and return null package response.

src/GregClient/GregClient.cs
because the package manager client is currently built targeting .net 4.5 (as are other dynamo dlls) - simplest way to support tls 1.2 is to OR it with the the current security protocols the `servicePointManager` supports.
https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager?redirectedfrom=MSDN&view=netframework-4.7.2
After this small change - rebuilding this dll, and adding it to dynamoCore's directory, wireshark shows the following for interactions with the dev package manager as of today.
@Dewb @ramramps @Racel
=> support TLS 1.2

src/GregClient/GregClient.csproj, src/GregClient/NuGet/GregClient.nuspec, src/GregClient/Properties/AssemblyInfo.cs, src/GregClient/Utility/FileUtilities.cs, src/GregClient/packages.config
Unzipping downloaded packages has been tested, zipping is untested until I am back on a machine with Revit/OAuth.
This bumps the Greg nuget version to 1.1.x.
=> Remove Ionic.Zip and use System.IO.Compression to handle zip/unzip

src/GregClient.sln, src/GregClient/CreateNugetPackage.ps1, src/GregClient/GregClient.csproj, src/GregClient/Properties/AssemblyInfo.cs, src/GregClient/Properties/globalVersionInfo.cs, src/GregClient_net45/GregClient_net45.csproj, src/GregClient_net45/Properties/AssemblyInfo.cs
This PR adds a new project to the package manager client solution - 
a legacy GregClient_net45 project. This is not ideal. 
At first I tried to use the `<targetFrameworks>` attribute as described here:
https://docs.microsoft.com/en-us/dotnet/standard/frameworks
sounds great .... it's not so simple of course - nuget restore is immediately busted. The solution crashes VS 2017(latest updates) whenever you try to clean or rebuild the solution. I found a few github issues reporting similar things from last year. If this was a project we updated more or if we intended to have more multi targeting I might look further, but I'm just not sure this feature of csproj files works very well with vs yet.
Instead I just added this extra project - it links to all the existing files of the regular …
=> add net45 targeting to Greg.dll so we can consume latest fixes in older Dynamo versions

src/GregClient/GregClient.cs, src/GregClient_net45/GregClient_net45.csproj
net 45 version of Greg should not let the OS decided what TLS to use and should always enforce TLS 1.2
.net 47 dll
.net 45 dll
@QilongTang @Dewb
=> net45 build should enforce TLS 1.2 always

src/GregClient/Requests/PackageUploadRequestBody.cs, src/GregClient/Requests/PackageVersionUploadRequestBody.cs
This PR reverts some API changes by adding back old constructors:
https://www.fuget.org/packages/Greg/1.2.7121.21318/lib/net47/diff/1.1.7074.39323/
@QilongTang PTAL - if this is good to go I'll push a new version of this to nuget, and we can integrate whenever.
=> add back the old constructors and use them

src/GregClient/Requests/PackageUploadRequestBody.cs, src/GregClient/Requests/PackageVersionUploadRequestBody.cs
@QilongTang 
In Dynamo we make a call like this:
```
var pkgHeader = File.ReadAllText(headerPath);
var body = JsonConvert.DeserializeObject<PackageUploadRequestBody>(pkgHeader);
```
which deserializes some json text into a packageUploadRequest which we then turn into a package.
This `DeserializeObject` call requires that the object type it tries to deserialize has a constructor which can be called by Json.net.
Since we now have two constructors (old and new api) it doesn't know which to call and throws. So we add an empty constructor, Json.net prefers this, calls it, and then iterates over all the properties in the json trying to call public setters. It just so happens that works great because all the property names in the json match the property names in c#.
=> add empty default constructor for json.net to use.

src/GregClient/App.config, src/GregClient/GregClient.cs, src/GregClient/Requests/JSONRequest.cs, src/GregClient/Requests/PackageUpload.cs, src/GregClient/Requests/PackageVersionUpload.cs, src/GregClient/Utility/Utilities.cs
Issue:
Large packages are failing on upload.
Package size around 85 Mb takes over 100 seconds to upload.
The default RestRequest.Timeout is 100 seconds. (https://docs.microsoft.com/en-us/dotnet/api/system.net.httpwebrequest.timeout?redirectedfrom=MSDN&view=netframework-4.8#System_Net_HttpWebRequest_Timeout)
Solution:
Set the default Timeout to 300 seconds and also add possibility to increase Timeout from App settings.
=> Set timout propery to RestRequests

src/GregClient/Converters/DependencyConverter.cs, src/GregClient/GregClient.csproj, src/GregClient/Requests/HeaderVersionDownload.cs, src/GregClient/Responses/Responses.cs, src/GregClientSandbox/Program.cs, src/GregClient_net45/GregClient_net45.csproj
This adds a request type HeaderVersionDownload that supports either:
- package id, package version
- engine, package name, package version
The response is a PackageVersion, which will contain just the ids for
dependencies, but preserves the existing structure. This is achieved by
using custom JSON deserialization with DependencyConverter.
=> Expose endpoints to get package version metadata

src/GregClient/GregClient.csproj, src/GregClient/Properties/globalVersionInfo.cs, src/GregClient/Requests/GetMaintainers.cs, src/GregClientSandbox/Program.cs, src/GregClient_net45/GregClient_net45.csproj
Exposing endpoint to get maintainers of a specific package provided its name and engine.
=> Exposing endpoint to get maintainers of a package in Greg

nuspec/GregClient.nuspec, src/GregClient.sln, src/GregClient.sln.DotSettings, src/GregClient/GregClient.cs, src/GregClient/GregClient.csproj, src/GregClient/Properties/globalVersionInfo.cs, src/GregClient/Requests/RequestBody.cs, src/GregClient/packages.config, src/GregClientSandbox/GregClientSandbox.csproj, src/GregClientSandbox/Program.cs, src/GregClientSandbox/packages.config, src/GregClient_net45/GregClient_net452.csproj
This PR updates restsharp in this repo to 106.12.0 - I will send followups to GregOAuth and Dynamo at the minimum - likely also DynamoRevit.
* updates nuget package refs
* updates target framework of net45 target to net452 - as RestSharp no longer supports net45. (Revit 2016)
* updates nuspec with better dependency groups based on .net target version
* update copyright year.
* fix some changed namespaces in restsharp.
=> update restsharp to latest stable 106.12.0

nuspec/ManualBuildPackage.ps1, src/GregClient/Requests/PackageUploadRequestBody.cs, src/GregClient/Requests/PackageVersionUploadRequestBody.cs, src/GregClientSandbox/Program.cs
Added copyright fields to the metadata to be serialized (Will not be uploaded yet)
=> Add Copyright Holder and Year fields 

src/GregClient/Responses/Responses.cs
Add the Copyright properties to the Package version response in order to be consumed in the UI like Dynamo
@QilongTang
@RobertGlobant20 @filipeotero
=> Add Copyright properties to the response

src/AssemblyInfoGenerator/AssemblyInfo.cs, src/AssemblyInfoGenerator/AssemblyInfo.tt, src/GregClient/AuthProviders/IAuthProvider.cs
https://jira.autodesk.com/browse/DYN-4771
add interface to allow integrators access to bearer token so it can be used to take advantage of single sign on within a graph.
update version number
=> get token interface

src/AssemblyInfoGenerator/AssemblyInfo.cs, src/AssemblyInfoGenerator/AssemblyInfo.tt, src/GregClient/GregClient.csproj
Add the dotnet 6.0 as a new target framework for the Greg Client nuget package
@mjkkirschner 
@jasonstratton
=> Add net6.0 as a target framework

pipeline.yml
Black Duck scans have been failing due to the slash direction, fixing to make the scans explore the build directory as well.
=> Fix output path for black duck scans

pipeline.yml
Switch to msbuild as dotnet build skips text templating, causing the revision number of the final package to be unchanged.
=> Temporary switch to msbuild to enable text templating

src/GregClient/Requests/PackageUploadRequestBody.cs, src/GregClient/Requests/PackageVersionUpload.cs, src/GregClient/Requests/PackageVersionUploadRequestBody.cs, src/GregClient/Responses/Responses.cs, src/GregClientTests/GregClientTests.cs
Adding compatibility matrix to PMClient with deserialization so Dynamo gets a collection of different compatibility info instead of a string.
The PR introduces changes to the compatibility schema:
The changes are not huge, it is proposed to change the json structure from a dictionary to an array of objects, reason behind this is since we need to deserialize this json property into a dictionary, we will also need to convert it into an observable collection when consuming it in Dynamo, an Observable Dictionary is more complex and will probably require creating this Observable Dictionary class from scratch, I feel using an already existing Observable Collection makes more sense.
The schema [wiki](https://wiki.autodesk.com/display/GEN/Dynamo+Package+Compatibility+Schema) has been updated with …
=> DYN-7471 Add compatibility matrix deserialization

src/GregClient/Requests/GetCompatibilityMap.cs, src/GregClientTests/GregClientTests.cs
`GetCompatibilityMap` should call the /host_map route on package manager and return host mapping in Greg.
@DynamoDS/dynamo 
@dnenov
=> DYN-7571 Add Compatibility Map route as an API
