- src/GregClient.sln
- src/GregClientSandbox/GregClientSandbox.csproj
Hi @pboyer, just minor project/solution tweaks. Please take a look, thanks!
> Removed "Mixed Platforms" and "x86" configs

- src/GregClient/AuthProviders/BasicProvider.cs
- src/GregClient/GregClient.cs
- src/GregClient/GregClient.csproj
- src/GregClient/packages.config
- src/GregClientSandbox/GregClientSandbox.csproj
- src/GregClientSandbox/app.config
Includes:
- Code fixes for RestSharp 105.2.3.0 compatibility
- Referencing RestSharp NuGet packages
@ikeough
> Code fixes for RestSharp 105.2.3.0 compatibility

- src/GregClient/GregClient.csproj
- src/GregClient/PackageManagerClient.cs
- src/GregClient/Requests/PackageManagerRequest.cs
Purpose:
New PackageManagerClient added to existing GregClient project.
-New PackageManagerClient is REST client for ACG API.
-It has only one Request type which returns the dynamic type in response.
Reviewers
@sharadkjaiswal
> Added new client for ACG API

- README.md
Please feel free up update the wording as necessary, but the link is to fulfill the _Built with Forge_ Bronze requirements around _Transparency and Choice_, _Privacy by Design_ for the Package Manger, DYN-1356
> Added link to Autodesk Privacy Policy to the readme.

- README.md
Per @marrg, "This is now a private repo."
> Removed reference/link to Package Manager source

- src/GregClient/GregClient.cs
- src/GregClient/Requests/PackageUpload.cs
- src/GregClient/Requests/PackageVersionUpload.cs
- src/GregClient/Requests/Request.cs
- src/GregClient/Responses/Responses.cs
https://jira.autodesk.com/browse/DYN-1795
> move to body

- src/GregClient/Properties/globalVersionInfo.cs
- src/GregClient/Requests/PackageUploadRequestBody.cs
- src/GregClient/Requests/PackageVersionUploadRequestBody.cs
- src/GregClient/Responses/Responses.cs
- src/GregClientSandbox/Program.cs
Adding host dependencies into the Greg C# Client so user would be able to upload package with host_dependencies specified. This is required by https://jira.autodesk.com/browse/DYN-1979.
FYI: @pinzart
> Adding Host Dependencies

- src/GregClient/GregClient.csproj
- src/GregClient/Requests/Hosts.cs
- src/GregClientSandbox/Program.cs
Add `Hosts` request to be consumed as static list
> add hosts request

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/PackageManagerClientMSbuild.yml
Add Github Action for VS2019 build and PR template.
> Add Github Action

- src/GregClient/GregClient.csproj
- src/GregClient/Properties/globalVersionInfo.cs
- src/GregClient/Requests/WhitelistHeaderCollectionDownload.cs
- src/GregClient/Responses/Responses.cs
- src/GregClient/Whitelist.cs
- src/GregClientSandbox/Program.cs
- src/GregClient_net45/GregClient_net45.csproj
This reverts commit 19e3966b64447fdd98c96112b66fc27224fa20b5.
Need to fix the version format.
> Revert "[DYN-2848] Remove Whitelist class and API (#40)"

- pipeline.yml
(FILL ME IN) This section describes why this PR is here. Usually it would include a reference 
to the tracking task that it is part or all of the solution for.
> switch to harmony

- Jenkinsfile
- pipeline.yml
- Changing node to use label "DynamoGPUWin".
- Adding step in Jenkinsfile to print all environment variables after build.
@QilongTang 
> Change job to use node labels

- pipeline.yml
Updates to scanning configuration
> Use external repo name for harmony.

- .github/workflows/PackageManagerClientMSbuild.yml
(FILL ME IN) This section describes why this PR is here. Usually it would include a reference 
to the tracking task that it is part or all of the solution for.
> use windows-2019 in git workflows

- cicdscripts/ProcessNugetPackage.ps1
- src/AssemblyInfoGenerator/AssemblyInfo.cs
- src/AssemblyInfoGenerator/AssemblyInfo.tt
- src/AssemblyInfoGenerator/AssemblyInfoGenerator.csproj
- src/GregClient.sln
- src/GregClient/GregClient.csproj
- src/GregClient/Properties/AssemblyInfo.cs
- src/GregClient/Properties/globalVersionInfo.cs
- src/GregClient/Utility/Utilities.cs
Refactor versioning so that it can work with multitargeting. The version should be auto incremented but stable between target frameworks
> refactor versioning

- src/GregClient/GregClient.csproj
(FILL ME IN) This section describes why this PR is here. Usually it would include a reference 
to the tracking task that it is part or all of the solution for.
> add description back and fix newtonsoft

- src/AssemblyInfoGenerator/AssemblyInfo.tt
Revert revision number to 3 hour interval
@mjkkirschner @QilongTang
> Revert revision number to 3 hour interval

- cicdscripts/BuildSolution.ps1
> Move to new build image.

- .github/workflows/PackageManagerClientMSbuild.yml
- README.md
- cicdscripts/BuildSolution.ps1
* Move to VS2022 and V1.2.2 (I missed to merge this back in January for some reason)
> Move to VS 2022

- cicdscripts/BuildSolution.ps1
> Use latest build image

- src/GregClient/Requests/UserVotes.cs
A small PR based on the new API route provided by @zeusongit `user/votes`. Will fetch all votes made by current user. 
- add route to fetch votes made by current user
@zeusongit 
@QilongTang
> Add request to fetch votes made by current user

- src/GregClient/Responses/Responses.cs
To handle response from user/votes route.
> Add user votes response class

- .github/workflows/PackageManagerClientMSbuild.yml
- README.md
- add `pull_request` trigger
- add setup msbuild step
- update path in check for Greg.dll step to look in net6.0 folder
- format workflow file
- remove obsolete info from README.md
@DynamoDS/dynamo 
> Update build workflow

- pipeline.yml
> Update scan schedule

- src/GregClient/AuthProviders/IAuthProvider.cs
Add new interface IOAuth2UserIDProvider
@zeusongit @mjkkirschner
> Add new interface IAuthProviderUserAccount

- pipeline.yml
This is breaking the build, since master branch is being treated as an RC branch
@reddyashish @mjkkirschner
> Remove master branch as release branch

- pipeline.yml
Currently scans donot find any files, support team suggetsed to remove extra slashes
> Fix BlackDuck scans

- pipeline.yml
Fixing the build command to match msbuild syntax
> Update build command

- pipeline.yml
The perf machines in the Boston office currently have no access to SonarQube. Ticket has been filed.
> Use common build machines

- pipeline.yml
> Testing dotnet Scanner for @sm6srw

- pipeline.yml
SonarQube command update. 
@sm6srw
> DYN-7116: SonarQube command update and remove dotnet coverage script.

- pipeline.yml
[DYN-7017](https://jira.autodesk.com/browse/DYN-7017)
> DYN-7017 Remove trailing slash in harmony scan dir

- src/GregClient/Requests/PackageVersionUploadRequestBody.cs
- src/GregClientTests/GregClientTests.cs
Add release notes URL and compatibility matrix properties to Package Version Header
> DYN-7413 Add release notes URL and compatibility matrix properties to Package Version Header

- src/GregClient/Requests/PackageUploadRequestBody.cs
- src/GregClient/Requests/PackageVersionUploadRequestBody.cs
- src/GregClient/Responses/Responses.cs
- src/GregClientTests/GregClientTests.cs
Adding release notes url to response
@QilongTang
> Add release notes property to response
